tournament:
  name: "tournament_resnet_4_64"
  max_nodes: 200
  rounds: 200
  batch_size: 64

models:
  resnet_4_64: 
    config: "resnet_4_64.yaml"
    start_gen: 0
    end_gen: 100
    step_gen: 1

  